### ISSUE TITLE
Typo in the README.md: `assert called` and not `assert_called`

### ISSUE THREAD

**Issue by joebew42** [jjh42/mock#90]
It seems there is a typo in the readme. Basically in the examples you wrote `assert_called`, but the correct one should be `assert called`. Is it right?

Thank you :rocket:

**Comment by Olshansk** [comment]
Nope, it was a recent change made by @mtrudel. Please see https://github.com/jjh42/mock/pull/87

**Comment by joebew42** [comment]
Oh cool! Thank you :+1:

**Comment by bessey** [comment]
I just ran into the same issue. While that may be the case @Olshansk, the problem is it is a recent _unreleased_ change. Personally I think it is incorrect to have your master branch documentation be referring to an as yet unreleased version of the library, at least with no note.

Perhaps a header with a link to the [currently released Hex docs](https://hexdocs.pm/mock/Mock.html) would be appreciated for the next person that hits this issue?
